language: swift
osx_image: xcode6.4 
 
 before_install:
   - gem install cocoapods -v '0.38.2'
   - pod install
      
   script:
        - xctool -workspace ios9WebviewSample.xcworkspace -scheme ios9WebviewSample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
              
   after_success:
        - echo "success"

   after_failure:
      - echo "failure"



